update

# add repositories
tap homebrew/binary
tap caskroom/homebrew-cask

install jq
install git
install wget
install tmux
install hub
install vim --devel --with-lua
install zsh
install subversion
install mercurial
install pyenv
install openssl
install readline
install rbenv
install ruby-build

cleanup

# install brew-cask
install brew-cask

# cask install
cask install alfred
cask install google-chrome
cask install google-japanese-ime
cask install iterm2
cask install appcleaner
cask install dropbox
cask install mou
cask install vagrant
cask install virtualbox
cask install xtrafinder
cask install evernote
cask install firefox
cask install kobito
cask install skitch
cask install appcode
cask install cyberduck
cask install intellij-idea
cask install lightpaper
cask install pycharm
cask install silverlight
cask install sizeup
cask install sublime-text
cask install onepassword
cask install cloud
cask install clipmenu
cask install sophos-anti-virus-home-edition
cask install cd-to
cask install r
cask install rstudio
cask install rescuetime
cask install sequel-pro
cask install sourcetree

cask alfred link

cask cleanup